import {
  BookOpen,
  FileText,
  Send,
  Award,
  Plane,
  MapPin,
  GraduationCap,
  Bell,
  Search,
  Users,
  Briefcase,
  Building,
  Globe,
  Calendar,
  Clock,
  CheckCircle,
  Star,
  Heart,
  Shield,
  Target,
  Zap,
  Lightbulb,
  Rocket,
  Anchor,
  Compass,
  Flag,
  Trophy,
  Medal,
  Gift,
  Package,
  ShoppingCart,
  CreditCard,
  Wallet,
  Calculator,
  BarChart,
  Settings,
  Edit,
  File,
  Folder,
  Camera,
  Image,
  Video,
  Music,
  Phone,
  Mail,
  Link,
  Download,
  Upload,
  Save,
  Plus,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Home,
  Eye,
  Maximize,
  Minimize,
  Sun,
  Moon,
  Cloud,
  Battery,
  Monitor,
  Smartphone,
  Laptop,
  Truck,
  Car,
  Ship
} from "lucide-react"

export interface IconOption {
  name: string
  displayName: string
  component: React.ComponentType<{ className?: string }>
}

export const ICON_OPTIONS: IconOption[] = [
  { name: "book-open", displayName: "Book Open", component: BookOpen },
  { name: "file-text", displayName: "File Text", component: FileText },
  { name: "send", displayName: "Send", component: Send },
  { name: "award", displayName: "Award", component: Award },
  { name: "plane", displayName: "Plane", component: Plane },
  { name: "map-pin", displayName: "Map Pin", component: MapPin },
  { name: "graduation-cap", displayName: "Graduation Cap", component: GraduationCap },
  { name: "bell", displayName: "Bell", component: Bell },
  { name: "search", displayName: "Search", component: Search },
  { name: "users", displayName: "Users", component: Users },
  { name: "briefcase", displayName: "Briefcase", component: Briefcase },
  { name: "building", displayName: "Building", component: Building },
  { name: "globe", displayName: "Globe", component: Globe },
  { name: "calendar", displayName: "Calendar", component: Calendar },
  { name: "clock", displayName: "Clock", component: Clock },
  { name: "check-circle", displayName: "Check Circle", component: CheckCircle },
  { name: "star", displayName: "Star", component: Star },
  { name: "heart", displayName: "Heart", component: Heart },
  { name: "shield", displayName: "Shield", component: Shield },
  { name: "target", displayName: "Target", component: Target },
  { name: "zap", displayName: "Zap", component: Zap },
  { name: "lightbulb", displayName: "Lightbulb", component: Lightbulb },
  { name: "rocket", displayName: "Rocket", component: Rocket },
  { name: "anchor", displayName: "Anchor", component: Anchor },
  { name: "compass", displayName: "Compass", component: Compass },
  { name: "flag", displayName: "Flag", component: Flag },
  { name: "trophy", displayName: "Trophy", component: Trophy },
  { name: "medal", displayName: "Medal", component: Medal },
  { name: "gift", displayName: "Gift", component: Gift },
  { name: "package", displayName: "Package", component: Package },
  { name: "shopping-cart", displayName: "Shopping Cart", component: ShoppingCart },
  { name: "credit-card", displayName: "Credit Card", component: CreditCard },
  { name: "wallet", displayName: "Wallet", component: Wallet },
  { name: "calculator", displayName: "Calculator", component: Calculator },
  { name: "bar-chart", displayName: "Bar Chart", component: BarChart },
  { name: "settings", displayName: "Settings", component: Settings },
  { name: "edit", displayName: "Edit", component: Edit },
  { name: "file", displayName: "File", component: File },
  { name: "folder", displayName: "Folder", component: Folder },
  { name: "camera", displayName: "Camera", component: Camera },
  { name: "image", displayName: "Image", component: Image },
  { name: "video", displayName: "Video", component: Video },
  { name: "music", displayName: "Music", component: Music },
  { name: "phone", displayName: "Phone", component: Phone },
  { name: "mail", displayName: "Mail", component: Mail },
  { name: "link", displayName: "Link", component: Link },
  { name: "download", displayName: "Download", component: Download },
  { name: "upload", displayName: "Upload", component: Upload },
  { name: "save", displayName: "Save", component: Save },
  { name: "plus", displayName: "Plus", component: Plus },
  { name: "check", displayName: "Check", component: Check },
  { name: "alert-circle", displayName: "Alert Circle", component: AlertCircle },
  { name: "info", displayName: "Info", component: Info },
  { name: "help-circle", displayName: "Help Circle", component: HelpCircle },
  { name: "home", displayName: "Home", component: Home },
  { name: "eye", displayName: "Eye", component: Eye },
  { name: "sun", displayName: "Sun", component: Sun },
  { name: "moon", displayName: "Moon", component: Moon },
  { name: "cloud", displayName: "Cloud", component: Cloud },
  { name: "battery", displayName: "Battery", component: Battery },
  { name: "monitor", displayName: "Monitor", component: Monitor },
  { name: "smartphone", displayName: "Smartphone", component: Smartphone },
  { name: "laptop", displayName: "Laptop", component: Laptop },
  { name: "truck", displayName: "Truck", component: Truck },
  { name: "car", displayName: "Car", component: Car },
  { name: "ship", displayName: "Ship", component: Ship }
]

export const getIconByName = (name: string): React.ComponentType<{ className?: string }> => {
  const iconOption = ICON_OPTIONS.find(option => option.name === name)
  return iconOption ? iconOption.component : BookOpen // Default fallback
}

export const getIconOptionByName = (name: string): IconOption | undefined => {
  return ICON_OPTIONS.find(option => option.name === name)
}
